#!/bin/bash

echo ""
# Verificar crontabs en el usuario actual
echo "Crontab del usuario actual ($USER):"
crontab -l
echo ""
echo ""

# Verificar crontabs de root
echo "Crontab de root:"
sudo crontab -l
echo ""
echo ""

# Verificar crontabs de todos los usuarios del sistema
echo "Crontabs de todos los usuarios del sistema:"
for username in $(cut -d: -f1 /etc/passwd); do
    echo "Usuario: $username"
    sudo crontab -u $username -l
    echo ""
done

