#!/bin/bash

sudo apt install firewalld

# Limit SSH to the competition subnet
sudo firewall-cmd --permanent --zone=public --remove-service=ssh
sudo firewall-cmd --permanent --zone=public \
--add-rich-rule='rule family=ipv4 source address=172.20.240.0/22 service name=ssh log prefix="SSH Logs" level="notice" accept'
sudo firewall-cmd --reload
sudo firewall-cmd --list-all --zone=public

