#!/bin/zsh

mktem
cd "$(xclip -o -sel clip)"

git clone https://github.com/4rji/4rji.git
cd 4rji/

cp README.md binarios


#fix scripts
#sudo mv -f ~/4rji/binarios/* /usr/bin/
sudo cp -f binarios/* /usr/bin/

cd
echo "binarios actualizados y 4rji borrado"

