#!/bin/bash

# Update repositories
sudo apt update

# Install unattended upgrades
sudo apt-get install unattended-upgrades apt-listchanges

# Install prereqs for ToR
sudo apt install apt-transport-https

# Extract VERSION_CODENAME from /etc/os-release
VERSION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)

# Create the new file /etc/apt/sources.list.d/tor.list
echo "deb [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org $VERSION_CODENAME main" | sudo tee /etc/apt/sources.list.d/tor.list

echo "deb-src [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org $VERSION_CODENAME main" | sudo tee -a /etc/apt/sources.list.d/tor.list

# Add the GPG Key
wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | sudo tee /usr/share/keyrings/tor-archive-keyring.gpg >/dev/null

# Update repositories again
sudo apt update

# Install ToR and deb.torproject.org-keyring
sudo apt install tor deb.torproject.org-keyring

# Configure ToR
echo '## BASE CONFIG
Nickname
ContactInfo your@e-mail
ORPort 443
ExitRelay 0
SocksPort 0

## BANDWIDTH

## The config below has a maximum of 800GB

## (up/down) per month, starting on the 1st

## for exit traffic
##ExitRelay 1
##ExitPolicy accept *:*


## at midnight
#AccountingMax 800 GB
#AccountingStart month 1 0:00

## MONITORING

ControlPort 9051
CookieAuthentication 1' | sudo tee -a /etc/tor/torrc

# Enable ToR and restart
service tor enable
service tor start

echo "Abre el archivo /etc/tor/torrc para personalizar el relay"
