#!/bin/zsh

if [ $# -eq 0 ]; then
    echo "Usage: $0 filename"
    exit 1
fi

file=$1
line_number=1

if [ -f "$file" ]; then
    cat "$file" | while read line; do
        echo "linea $line_number"
        echo "$line"
        ((line_number++))
    done
else
    echo "File $file not found."
    exit 1
fi

