#!/bin/zsh

cd ~/4rji

#mover readme con lista en dos para 4rjic
./partir_readme
cp -f README.md ~/4rji/binarios/


#fix scripts
#sudo mv -f ~/4rji/binarios/* /usr/bin/
sudo cp -f ~/4rji/binarios/* /usr/bin/
cd ..

cd ~
rm -rf 4rji
echo "binarios actualizados y 4rji borrado"

